name: Test Microsoft Graph

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
            }
          allow-no-subscriptions: true

      - name: Hämta kalender från Graph
        run: |
          TOKEN=$(az account get-access-token --resource-type ms-graph --query accessToken -o tsv)

          curl \
            -H "Authorization: Bearer $TOKEN" \
          https://graph.microsoft.com/v1.0/groups/8ae31d92-e3ad-4210-ae24-8681fb858c4d/calendar
