name: Test Microsoft Graph

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
            }
          allow-no-subscriptions: true

      - name: Test Azure CLI
        run: |
          az account show
